
import { GoogleGenAI } from "@google/genai";
import { AspectRatio, ImageSize, VideoResolution } from "../types";

export const generate3DIcon = async (
  prompt: string,
  config: { aspectRatio: AspectRatio; imageSize: ImageSize }
): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3-pro-image-preview',
      contents: {
        parts: [{ text: prompt }],
      },
      config: {
        imageConfig: {
          aspectRatio: config.aspectRatio,
          imageSize: config.imageSize,
        },
      },
    });

    const candidates = response.candidates;
    if (!candidates || candidates.length === 0) {
      throw new Error("No image generated by the model.");
    }

    for (const part of candidates[0].content.parts) {
      if (part.inlineData) {
        const base64EncodeString = part.inlineData.data;
        return `data:image/png;base64,${base64EncodeString}`;
      }
    }

    throw new Error("Response did not contain an image part.");
  } catch (error: any) {
    if (error.message?.includes("Requested entity was not found")) {
        throw new Error("API_KEY_ERROR");
    }
    throw error;
  }
};

export const generateAnimatedIcon = async (
  prompt: string,
  config: { aspectRatio: '16:9' | '9:16'; resolution: VideoResolution },
  onStatusUpdate?: (status: string) => void
): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  try {
    onStatusUpdate?.("Initializing Veo generation...");
    let operation = await ai.models.generateVideos({
      model: 'veo-3.1-fast-generate-preview',
      prompt: prompt,
      config: {
        numberOfVideos: 1,
        resolution: config.resolution,
        aspectRatio: config.aspectRatio
      }
    });

    while (!operation.done) {
      onStatusUpdate?.("Veo is processing... this may take 1-2 minutes.");
      await new Promise(resolve => setTimeout(resolve, 10000));
      operation = await ai.operations.getVideosOperation({ operation: operation });
    }

    const downloadLink = operation.response?.generatedVideos?.[0]?.video?.uri;
    if (!downloadLink) {
      throw new Error("No video generated.");
    }

    onStatusUpdate?.("Finalizing video assets...");
    const response = await fetch(`${downloadLink}&key=${process.env.API_KEY}`);
    const blob = await response.blob();
    return URL.createObjectURL(blob);
  } catch (error: any) {
    if (error.message?.includes("Requested entity was not found")) {
        throw new Error("API_KEY_ERROR");
    }
    throw error;
  }
};
